// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr5RzyfsZHj6iIIGB8tUeALLt_w4Wgpf8',
    appId: '1:308628032795:web:865d6f07b368f0195357be',
    messagingSenderId: '308628032795',
    projectId: 'saglik-yaninda-ec8d2',
    authDomain: 'saglik-yaninda-ec8d2.firebaseapp.com',
    storageBucket: 'saglik-yaninda-ec8d2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBsPdBBnidW4fbtU0rhFh6OZBGSkk9aJE',
    appId: '1:308628032795:android:e5cb96a23829c85e5357be',
    messagingSenderId: '308628032795',
    projectId: 'saglik-yaninda-ec8d2',
    storageBucket: 'saglik-yaninda-ec8d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0StW-ArlDLa4Cmx__S-KzFD_l749UI88',
    appId: '1:308628032795:ios:ddf23024da23bf1d5357be',
    messagingSenderId: '308628032795',
    projectId: 'saglik-yaninda-ec8d2',
    storageBucket: 'saglik-yaninda-ec8d2.firebasestorage.app',
    iosBundleId: 'com.example.saglikYaninda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0StW-ArlDLa4Cmx__S-KzFD_l749UI88',
    appId: '1:308628032795:ios:ddf23024da23bf1d5357be',
    messagingSenderId: '308628032795',
    projectId: 'saglik-yaninda-ec8d2',
    storageBucket: 'saglik-yaninda-ec8d2.firebasestorage.app',
    iosBundleId: 'com.example.saglikYaninda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr5RzyfsZHj6iIIGB8tUeALLt_w4Wgpf8',
    appId: '1:308628032795:web:74f3c4f9b985cdb15357be',
    messagingSenderId: '308628032795',
    projectId: 'saglik-yaninda-ec8d2',
    authDomain: 'saglik-yaninda-ec8d2.firebaseapp.com',
    storageBucket: 'saglik-yaninda-ec8d2.firebasestorage.app',
  );

}